### Session1 深度学习框架
Pytorch
2018, 12 1.0 
2019.5 1.1 

Google: Theano-> TensorFlow 1 -> TF2 -> keras <br>
Facebook: Torch7-> Caffe-> Pytorch + Caffe2 <br>
Amazon: MxNet
### Session 2 深度学习初见
### Session 3 基础张量操作
https://github.com/dragen1860/Deep-Learning-with-PyTorch-Tutorials/blob/master/lesson06-基本数据类型/lesson6.pdf

In [ ]:
Pytorch
int
float
int array
float array
一个数据被放在不同的地方他的数据类型可能会不一样
放在GPU上会多一个cuda


In [5]:
import torch
a =torch.rand(2,3)
print (a.type())
print (type(a)) ## did not provide additional info

torch.FloatTensor
<class 'torch.Tensor'>


In [6]:
isinstance(a, torch.FloatTensor)

True

In [7]:
isinstance(a, torch.cuda.FloatTensor)

AssertionError: Torch not compiled with CUDA enabled

### 标量 长度为0 ， 用（）
loss 经常用标量表示

In [8]:
torch.tensor(1.)

tensor(1.)

In [9]:
torch.tensor(1.3)

tensor(1.3000)

In [21]:
a = torch.tensor(2.3)
print (a.shape)
print (len(a.shape))
print (a.size())
print (a)


torch.Size([])
0
torch.Size([])
tensor(2.3000)


### Dim 为1 的张量 长度为1， 用[ ] 表示 
在python里叫做 dim 为1 的vector， 在pytorch里不管dim统一叫做张量 <br>

dimension 指的是行数或者列数 ：[2,2] dimension is 2<br>
size 指的是具体的shape : [2,2] 2*2 <br>

bias 常用1维的tensor <br>
一个linear input ：[28*28] image = 784 的vector

In [14]:
torch.tensor([1.1])

tensor([1.1000])

In [15]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [16]:
torch.FloatTensor(1)## random 初始化

tensor([0.])

In [17]:
torch.FloatTensor(2)## random 初始化

tensor([ 0.0000e+00, -3.6893e+19])

In [19]:
import numpy as np
data =np.ones(2)
data

array([1., 1.])

### 从Numpy导入

In [20]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

### Dim 2 的tensor
linear input batch：  多个linear input [4, 784] 四个 28*28 flatten了的图片

In [22]:
a = torch.rand(2,3)
a

tensor([[0.3292, 0.7860, 0.5035],
        [0.3463, 0.4908, 0.4488]])

In [23]:
a.shape

torch.Size([2, 3])

In [24]:
a.size()

torch.Size([2, 3])

In [25]:
print (a.shape[0], a.size()[0], a.shape[1], a.size()[1])

2 2 3 3


### Dim 3 的tensor
RNN input batch [10 word per sentences  , batch  size  10 sentences,  word vector]

In [26]:
a = torch.rand(1,2,3)
##随机0-1 的均匀分布
a
## 一个两行三列的

tensor([[[0.2013, 0.4896, 0.8861],
         [0.9333, 0.9524, 0.6036]]])

In [27]:
a[0]
##少一个中括号， 第一个维度的 第0个元素 ，也只有第0个元素

tensor([[0.2013, 0.4896, 0.8861],
        [0.9333, 0.9524, 0.6036]])

In [28]:
a.shape

torch.Size([1, 2, 3])

In [29]:
## tensor 的shape可以easy的转换成 list
list(a.shape)

[1, 2, 3]

### Dim 4 的tensor
CNN: [batch, channel, height, wideth]

In [30]:
a = torch.rand(2,3, 28, 28)
a.shape

torch.Size([2, 3, 28, 28])

In [31]:
list(a.shape)

[2, 3, 28, 28]

### tensor的大小和dim

In [32]:
a.numel()
#2*3*28*28 占用这么大的内存

4704

In [33]:
a.dim()

4

### 创建tensor
torch.tensor([2.,3.2])  <br>
torch.FloatTensor(dim1, dim2) <br>
torch.IntTensor(dim1, dim2) <br>
torch.tensor([[2., 3.2], [1.,22.3]])

In [43]:
a=torch.tensor([2.,3.2])
print (a)
print (a.dim())

tensor([2.0000, 3.2000])
1


In [40]:
torch.FloatTensor([2.,3.2])
##不推荐用这种方法，一般FloatTensor 的input是shape， 如下

tensor([2.0000, 3.2000])

In [36]:
torch.FloatTensor(2, 3)

tensor([[ 0.0000e+00, -3.6893e+19,  2.9442e-27],
        [-3.6902e+19,  2.8026e-45, -3.6893e+19]])

In [41]:
a=torch.tensor([[2., 3.2], [1.,22.3]])

In [42]:
a.dim()

2

### uninitialized tensor
数字非常大，或者非常小，所以神经网络的最好自己初始化，不然会出现一些bug 数字太大或者太小

In [46]:
torch.empty(1)

tensor([0.])

In [47]:
torch.Tensor(2,3)
## 数字非常大，或者非常小，所以神经网络的最好自己初始化，不然会出现一些bug 数字太大或者太小

tensor([[ 0.0000e+00, -3.6893e+19,  0.0000e+00],
        [-3.6893e+19,  2.8026e-45, -3.6893e+19]])

In [48]:
torch.IntTensor(2,3)

tensor([[         0, -536870912,  325596533],
        [1073743870,          2,          0]], dtype=torch.int32)

### 设置默认的tensor类别
reinforce learning的时候常用double,精确度会比较高

In [50]:
torch.tensor([1.2,3]).type()

'torch.FloatTensor'

In [52]:
a=torch.tensor(2)
a.dim()

0

In [49]:
torch.Tensor(2)
##默认的大些Tensor 就是用的默认类型

tensor([ 0.0000e+00, -3.6893e+19])

In [53]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [54]:
torch.tensor([1.2,3]).type()

'torch.DoubleTensor'

In [55]:
torch.set_default_tensor_type(torch.FloatTensor)

In [56]:
torch.tensor([1.2,3]).type()

'torch.FloatTensor'

### 推荐的初始化方法
rand ( 0 to 1 uniform) <br>
[min, max)   torch.randint(1,10,[3,3])<br>
rand_like <br>
ones_like <br>
zeros_like <br>


torch.logspace(0,-1,steps=10) <br>
torch.linspace(0,10,steps=10) <br>

In [58]:
a=torch.rand(3,3)
a

tensor([[0.0589, 0.2624, 0.7330],
        [0.4525, 0.1056, 0.7184],
        [0.6720, 0.4334, 0.1570]])

In [60]:
torch.rand_like(a)
#自动读取a的shape 然后feed给rand_like


tensor([[0.7421, 0.7530, 0.6599],
        [0.2789, 0.3152, 0.1321],
        [0.1600, 0.0557, 0.2000]])

In [61]:
torch.randint(1,10,[3,3])
##可以取到1 但是不能取到10， 第三个参数是matrix的shape

tensor([[3, 1, 6],
        [9, 8, 1],
        [3, 2, 3]])

In [62]:
torch.linspace(0,10,steps=4)
##等分

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [63]:
torch.linspace(0,10,steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [64]:
torch.linspace(0,10,steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [67]:
torch.logspace(0,-1,steps=10)
#10 的0次方 到10 的-1 次方 等分

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [68]:
torch.logspace(0,1,steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

In [69]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [70]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [71]:
torch.eye(3,3)
##对角, 只能接受两维的，三维以上不可以

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [72]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [75]:
torch.randperm(10)
## 0 - 10 10 不包括

tensor([5, 1, 3, 6, 8, 7, 2, 0, 9, 4])

In [80]:
### 只shuffle 人，而不shuffle 他们的成绩

a =torch.rand(2,3)
b = torch.rand(2,2)
idx = torch.randperm(2)
idx

tensor([0, 1])

In [78]:
idx

tensor([1, 0])

In [81]:
a[idx]

tensor([[0.5458, 0.9528, 0.6029],
        [0.9397, 0.5740, 0.4286]])

In [82]:
b[idx]

tensor([[0.0062, 0.1381],
        [0.0367, 0.0735]])

In [83]:
a,b

(tensor([[0.5458, 0.9528, 0.6029],
         [0.9397, 0.5740, 0.4286]]), tensor([[0.0062, 0.1381],
         [0.0367, 0.0735]]))

### Indexing 
https://www.udemy.com/course/deeplearning-pytorch/learn/lecture/14396326#announcements

In [84]:
a=torch.rand(4, 3, 28, 28)
a [0].shape

torch.Size([3, 28, 28])

In [85]:
a[0,0].shape

torch.Size([28, 28])

In [86]:
a[0,0,2,4]

tensor(0.5279)

In [87]:
a [:2].shape
#前两张图片

torch.Size([2, 3, 28, 28])

In [88]:
a [:2, :1, :, :].shape
#前两张图片，第一个通道

torch.Size([2, 1, 28, 28])

In [89]:
a [:2, 1:, :, :].shape
#前两张图片，从第一个通道到最后一个通道

torch.Size([2, 2, 28, 28])

In [91]:
a [:2, -1:, :, :].shape
#前两张图片，从最后一个通道到最末尾通道

torch.Size([2, 1, 28, 28])

In [93]:
a [:, :, 0:28:2, 0:28:2].shape
#两个冒号：0 开头 28 结尾， 隔行采样

torch.Size([4, 3, 14, 14])

In [95]:
a [:, :, 0:28:3, 0:28:3].shape
#两个冒号：0 开头 28 结尾， 隔2行采样

torch.Size([4, 3, 10, 10])

In [94]:
a [:, :, ::2, ::2].shape
#两个冒号：从头到尾， 隔行采样

torch.Size([4, 3, 14, 14])

### index_select()

In [99]:
?a.index_select()

In [107]:
a.index_select(0,torch.tensor([0,1])).shape
##对0 维度进行select，对第0 和第1 张图片

torch.Size([2, 3, 28, 28])

In [109]:
a.index_select(0,torch.tensor(0)).shape

torch.Size([1, 3, 28, 28])

In [112]:
a.index_select(1,torch.tensor([1,2])).shape
##对第1个维度进行选择， 所以4张图片的 1， 2 两个通道

torch.Size([4, 2, 28, 28])

In [102]:
a.index_select(2, torch.arange(28)).shape
## 0 - 28 所有的行 【0，28】

torch.Size([4, 3, 28, 28])

In [113]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

In [114]:
a[...].shape
##任意多的维度 相当于多个：，配对，具体数量看情况

torch.Size([4, 3, 28, 28])

In [115]:
a[0,...].shape

torch.Size([3, 28, 28])

In [116]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [118]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

In [ ]:
### select by mask

In [120]:
x = torch.rand(3, 4)
x

tensor([[0.9272, 0.3799, 0.6244, 0.1942],
        [0.1580, 0.2921, 0.4936, 0.6266],
        [0.4087, 0.1598, 0.2631, 0.9463]])

In [122]:
mask = x.ge(0.5)
mask

tensor([[1, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1]], dtype=torch.uint8)

In [123]:
torch.masked_select(x, mask)
#会被打平，拿出所有》0.5的

tensor([0.9272, 0.6244, 0.6266, 0.9463])

In [124]:
torch.masked_select(x, mask).shape

torch.Size([4])

In [125]:
torch.masked_select(x, mask).dim()

1

In [127]:
src = torch.tensor([[4,3,5],[6,7,8]])
src

tensor([[4, 3, 5],
        [6, 7, 8]])

In [131]:
## 先把src 打平，然后按照位置取出
torch.take(src, torch.tensor([0,2,5]))

tensor([4, 5, 8])

### Tensor 维度变换
view/reshape <br>
Squeeze/unsqueeze <br>
Tranpose/t/permute <br>
Expand/repeat <br>
### view/reshape

In [132]:
a = torch.rand(4, 1, 28, 28)
a.shape

torch.Size([4, 1, 28, 28])

In [133]:
a.view(4, 28*28)
##每个图片就用784的pixel 表示，去掉位置的信息 适合fc input

tensor([[0.8997, 0.9420, 0.3054,  ..., 0.8333, 0.5351, 0.6049],
        [0.4286, 0.8968, 0.6702,  ..., 0.4210, 0.3793, 0.4938],
        [0.3157, 0.8507, 0.0737,  ..., 0.8965, 0.9016, 0.3270],
        [0.8627, 0.8607, 0.1507,  ..., 0.4380, 0.0827, 0.9816]])

In [134]:
a.view(4, 28*28).shape

torch.Size([4, 784])

In [135]:
a.view(4*28, 28).shape
##所有照片的行放在一起

torch.Size([112, 28])

In [137]:
a.view(4*1, 28, 28).shape
##把所有的feature map 拿出来

torch.Size([4, 28, 28])

In [139]:
b = a.view(4, 784)
b.shape

torch.Size([4, 784])

In [141]:
c =b.reshape(4, 28, 28, 1)
c.shape

torch.Size([4, 28, 28, 1])

### Squeeze/unsqueeze 
正负index 的对应关系： <br>
[-5, -4, -3, -2, -1]  对负数，表示在之后插入<br>
[0, 1, 2, 3, 4] 对正数，表示在之前插入

In [142]:
a.shape

torch.Size([4, 1, 28, 28])

In [143]:
a.unsqueeze(0).shape
## 1 表示一个组， 额外的一个维度
## 0 对正数，表示在之前插入

torch.Size([1, 4, 1, 28, 28])

In [144]:
a.unsqueeze(-1).shape
##在最后一个位置插入

torch.Size([4, 1, 28, 28, 1])

In [147]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [148]:
a.unsqueeze(3).shape

torch.Size([4, 1, 28, 1, 28])

In [149]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [154]:
a = torch.tensor([1.2, 2.3])
print (a.shape)
print (a.unsqueeze(-1).shape)

torch.Size([2])
torch.Size([2, 1])


In [155]:
a.unsqueeze(-1)
##插入在后面， 数据本身是不会变的

tensor([[1.2000],
        [2.3000]])

In [156]:
a.unsqueeze(0)

tensor([[1.2000, 2.3000]])

In [157]:
a.unsqueeze(0).shape
##插入在前面， 数据本身是不会变的

torch.Size([1, 2])

In [161]:
b = torch.rand(32)
f = torch.rand(4, 32, 14, 14)
print( b.unsqueeze(1).shape)
#1 之前插入， 总共只有1
print (b.unsqueeze(1).unsqueeze(2).shape)
#2 之前插入
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
#0 之前插入
b.shape

torch.Size([32, 1])
torch.Size([32, 1, 1])


torch.Size([1, 32, 1, 1])

### squeeze()不给参数，能挤压的（维度为1的）都挤压

In [162]:
b.squeeze().shape

torch.Size([32])

In [163]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [164]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [165]:
b.squeeze(1).shape
##不能挤压，就return 原来的，

torch.Size([1, 32, 1, 1])

In [166]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

### Expand /Repeat
Expand: 数据没有增加,不需要copy的时候不copy: 扩张前后，dim必须一致，参数是你要扩展到多大  <br>
Repeat: 数据进行了copy: ##repeat 的参数是每个维度上要repeat的次数, 会占用比较多的空间，不推荐

In [ ]:
a = torch.rand(4, 32, 14, 14)

In [167]:
b.shape

torch.Size([1, 32, 1, 1])

In [168]:
b.expand(4, 32, 14, 14).shape

torch.Size([4, 32, 14, 14])

In [169]:
b.expand(-1, 32, -1, -1).shape
## -1 表示这个维度不变
## 32 扩张成32 还是32

torch.Size([1, 32, 1, 1])

In [170]:
b.expand(-1, 32, -1, -4).shape
## -4 没有任何意义，但是还是会return 为-4

torch.Size([1, 32, 1, -4])

In [171]:
b.repeat(4, 32, 1, 1).shape
##repeat 的参数是每个维度上要repeat的次数

torch.Size([4, 1024, 1, 1])

In [172]:
b.repeat(4, 1, 1, 1).shape

torch.Size([4, 32, 1, 1])

In [173]:
b.repeat(4, 1, 32, 32).shape

torch.Size([4, 32, 32, 32])

### 转置
https://www.udemy.com/course/deeplearning-pytorch/learn/lecture/14396680#announcements

In [174]:
a = torch.randn(4, 3)
a.shape

torch.Size([4, 3])

In [175]:
a.t().shape
##转置只能用于2维的矩阵

torch.Size([3, 4])

In [177]:
a = torch.rand(4, 3, 32, 32)
a1 = a.transpose(1,3).view(4, 3*32*32).view(4,3,32,32)

RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/wheel_3.6/pytorch/aten/src/TH/generic/THTensor.cpp:213

In [181]:
print (a.transpose(1,3).shape)
print (a.transpose(1,3).view(4,3*32*32).shape)

torch.Size([4, 32, 32, 3])


RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/wheel_3.6/pytorch/aten/src/TH/generic/THTensor.cpp:213

In [178]:
a1 = a.transpose(1,3).contiguous().view(4, 3*32*32).view(4,3,32,32)
## a1 是不对的，和a不同
#[b c h w]-> [b w h c ]-> [b c w h]

In [187]:
a2 = a.transpose(1,3).contiguous().view(4, 3*32*32).view(4,32,32,3).transpose(1,3)
## a2 和a相同
#[b c h w]-> [b w h c ]-> [b w h c] -> [b c h w]

In [183]:
torch.all(torch.eq(a, a1))
## 用all来check a 和a1 是否一致

tensor(0, dtype=torch.uint8)

In [188]:
torch.all(torch.eq(a, a2))
# 0 代表不是全部一致， 1 代表全部一致

tensor(1, dtype=torch.uint8)

In [192]:
a = torch.rand(4, 3, 28, 28)
a.transpose(1,3).shape

torch.Size([4, 28, 28, 3])

In [193]:
b = torch.rand(4, 3, 28, 32)
b.transpose(1,3).shape

torch.Size([4, 32, 28, 3])

In [194]:
b.permute(0,2,3,1).shape
##permute 的参数是你想要变成的 index 的数字

torch.Size([4, 28, 32, 3])

### broadcast
https://www.udemy.com/course/deeplearning-pytorch/learn/lecture/14396936#announcements

有对tensor 加一个标量的需求（比如某一门课很难，大家都加5分），但是直接是不能加上去的

可以加的情况:
A: [ 4, 32, 14, 14]
b: [1, 32, 1, 1] => [4,32, 14, 14] 然后相加


A: [ 4, 32, 14, 14]
b: [14， 14] => [1，1, 14, 14] 然后相加，每个图片都每个channel都加上14， 14 


A: [ 4, 32, 14, 14]
b: [2， 32， 14， 14]  不能相加


[class, student, scores] + [scores]

[class, student, scores ] + [student, 1]

[4, 3, 32, 32] 
+  +[32, 32]  照片平移
+ +[3, 1, 1]
+ +[1,1,1,1] 



### Merge or split
+ Cat:   有cat的那个dim可以不一样，其他的都要一样
+ Stack: stack 会创建一个新的维度,两个要stack的东西维度必须一模一样
+ Split： 按照长度拆分，或者按照个数拆分
+ Chunk： 按照数量拆分

[class 2-4, students, scores]

[class 5-9, students, scores]

In [197]:
a = torch.rand(4,32, 8)
b = torch.rand(5,32,8)
torch.cat([a,b],dim=0).shape

## 如果要cat的话，只有cat的那个dim可以不一样，其他的都要一样

torch.Size([9, 32, 8])

In [201]:
a = torch.rand(4,3, 32, 32)
b = torch.rand(4,1, 32, 32)
torch.cat([a,b],dim=1).shape

torch.Size([4, 4, 32, 32])

In [202]:
a = torch.rand( 32, 8)
b = torch.rand( 32, 8)
torch.stack([a,b],dim=0).shape
## 在dim=0 之前插入一个新的维度

torch.Size([2, 32, 8])

In [207]:
c = torch.rand(3, 32, 8)
aa, bb = c.split([2,1], dim=0)
##split 按照个数拆分，在dim=0上操作
aa.shape, bb.shape

(torch.Size([2, 32, 8]), torch.Size([1, 32, 8]))

In [211]:
aa, bb, cc = c.split(1, dim=0)
##split 每个单元长度为1，在dim=0上操作
aa.shape, bb.shape,cc.shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

In [213]:
c = torch.rand(2, 32, 8)
aa, bb = c.chunk(2, dim=0)
aa.shape, bb.shape
##chunk 按照数量拆分，在dim=0上操作

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

### tensor 基本运算
https://www.udemy.com/course/deeplearning-pytorch/learn/lecture/14397178#announcements
+ Add/sub/mul/div:加减乘除
+ matmul
+ Pow
+ sqrt/rsqrt
+ Round: .floor(), .ceil(), .round, .trunnc(), .frac()

In [215]:
a = torch.rand(3,4)
b = torch.rand(4)
a, b, a+b

(tensor([[0.3925, 0.7058, 0.1626, 0.2015],
         [0.8821, 0.4771, 0.9974, 0.1229],
         [0.3731, 0.3158, 0.8817, 0.3406]]),
 tensor([0.3951, 0.9574, 0.2181, 0.7403]),
 tensor([[0.7875, 1.6631, 0.3807, 0.9418],
         [1.2771, 1.4345, 1.2155, 0.8632],
         [0.7681, 1.2732, 1.0998, 1.0808]]))

In [216]:
torch.add(a,b)

tensor([[0.7875, 1.6631, 0.3807, 0.9418],
        [1.2771, 1.4345, 1.2155, 0.8632],
        [0.7681, 1.2732, 1.0998, 1.0808]])

In [218]:
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(1, dtype=torch.uint8)

In [219]:
torch.all(torch.eq(a*b, torch.mul(a,b)))

tensor(1, dtype=torch.uint8)

In [220]:
torch.all(torch.eq(a/b, torch.div(a,b)))

tensor(1, dtype=torch.uint8)

### 矩阵乘法
+ Torch.mm: only for 2d 不推荐
+ Torch.matmul 对于高维的，计算的时候还是只取了最后的两维
+ @

In [221]:
a =torch.rand([2,2])
a

tensor([[0.2343, 0.0672],
        [0.8973, 0.9463]])

In [224]:
b = torch.ones([2,2])
b

tensor([[1., 1.],
        [1., 1.]])

In [226]:
a@b

tensor([[0.3016, 0.3016],
        [1.8436, 1.8436]])

In [227]:
torch.mm(a, b)

tensor([[0.3016, 0.3016],
        [1.8436, 1.8436]])

In [228]:
torch.matmul(a, b)

tensor([[0.3016, 0.3016],
        [1.8436, 1.8436]])

In [231]:
x = torch.rand(4, 784)## 4张照片，打平了， 希望降维
w = torch.rand (512, 784)
##本来应该是784， 512 但是pytorch要求是chout chin 所以.t()
##.t() 只能用于二维，高维的要用transpose
(x@w.t()).shape

torch.Size([4, 512])

In [232]:
a =torch.rand([4,3, 28,64])
b =torch.rand([4,3, 64,32])
torch.matmul(a,b).shape
##计算的时候还是只取了最后的两维

torch.Size([4, 3, 28, 32])

In [233]:
a =torch.rand([4,3, 28,64])
b =torch.rand([4,1, 64,32])
torch.matmul(a,b).shape
## 会用到broadcast

torch.Size([4, 3, 28, 32])

### Power


In [234]:
a = torch.full([2,2],3)
a

tensor([[3., 3.],
        [3., 3.]])

In [235]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [237]:
aa=a**2
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [238]:
aa.rsqrt()
##reverse 

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [239]:
a = torch.exp(torch.ones(2,2))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [240]:
torch.log(a)

tensor([[1.0000, 1.0000],
        [1.0000, 1.0000]])

In [241]:
a = torch.tensor(3.14)
a

tensor(3.1400)

In [244]:
a.floor(), a.ceil(), a.trunc(), a.frac(), a.round()#四舍五入

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400), tensor(3.))

### clamp gradient clipping 
梯度<10 比较合适 

In [247]:
grad = torch.rand(2,3)*15
grad.max()

tensor(12.5887)

In [248]:
grad.median()

tensor(6.6404)

In [250]:
grad

tensor([[ 3.3177,  6.6404,  1.7310],
        [12.1978, 12.3245, 12.5887]])

In [249]:
grad.clamp(10)
## 最小值限定为10

tensor([[10.0000, 10.0000, 10.0000],
        [12.1978, 12.3245, 12.5887]])

In [252]:
grad.clamp(0,10)
## 0 to 10

#for w in []:
    #clamp(w.grad, 10)

tensor([[ 3.3177,  6.6404,  1.7310],
        [10.0000, 10.0000, 10.0000]])

### 统计属性计算
https://www.udemy.com/course/deeplearning-pytorch/learn/lecture/14397186#announcements
+ norm： 范数，1 norm 所有绝对值相加， 2-norm 所有平方相加，在开根号， 3-norm ：绝对值三次方再开1/3
+ mean sum
+ prod
+ max, min, prod (全部元素相乘） argmin （会return 打平后的索引）, argmax
+ kthvalue, topk

In [255]:
a = torch.full([8], 1)
b = a.view (2,4)
c = a.view (2, 2,2)
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [256]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [258]:
a.norm(1),b.norm(1), c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [259]:
a.norm(2),b.norm(2), c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [260]:
b.norm(1, dim=1)

tensor([4., 4.])

In [261]:
b.norm(2, dim=1)

tensor([2., 2.])

In [262]:
c.norm(1, dim=0)

tensor([[2., 2.],
        [2., 2.]])

In [263]:
c.norm(2, dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

In [265]:
a = torch.rand(2,4)
a

tensor([[0.9953, 0.2641, 0.9869, 0.6183],
        [0.2826, 0.2408, 0.6562, 0.4303]])

In [267]:
a.argmax(), a.argmin()
##会打平

(tensor(0), tensor(5))

In [270]:
a = torch.rand(4,10)
print (a)
print (a[0])
a.argmax(dim=1), a.argmin(dim=1)
##4张照片，最大的概率的类别，最小概率的类别

tensor([[0.5774, 0.7515, 0.8563, 0.2250, 0.3197, 0.1155, 0.6165, 0.8676, 0.2171,
         0.9897],
        [0.6934, 0.3845, 0.1820, 0.4120, 0.5332, 0.9099, 0.8907, 0.3324, 0.5976,
         0.5443],
        [0.0353, 0.6544, 0.0460, 0.7757, 0.0104, 0.5841, 0.1869, 0.9311, 0.6368,
         0.9307],
        [0.4991, 0.9453, 0.7833, 0.9893, 0.9156, 0.3910, 0.9816, 0.0165, 0.4856,
         0.2865]])
tensor([0.5774, 0.7515, 0.8563, 0.2250, 0.3197, 0.1155, 0.6165, 0.8676, 0.2171,
        0.9897])


(tensor([9, 5, 7, 3]), tensor([5, 2, 4, 7]))

### dim, keep dim

In [271]:
a.max(dim=1)
#每张照片的最大的概率，和预测的label

(tensor([0.9897, 0.9099, 0.9311, 0.9893]), tensor([9, 5, 7, 3]))

In [272]:
a.max(dim=1, keepdim=True)

(tensor([[0.9897],
         [0.9099],
         [0.9311],
         [0.9893]]), tensor([[9],
         [5],
         [7],
         [3]]))

In [273]:
a.argmax(dim=1, keepdim=True)
##argmax 是max 结果的一部分

tensor([[9],
        [5],
        [7],
        [3]])

In [274]:
a.argmax(dim=1)

tensor([9, 5, 7, 3])

In [277]:
a.argmax(dim=1).unsqueeze(1)

tensor([[9],
        [5],
        [7],
        [3]])

### Top-k or k-th
对于这个照片， 取概率最大的k个

In [279]:
a.topk(3, dim=1)
##prod 最大的三个

(tensor([[0.9897, 0.8676, 0.8563],
         [0.9099, 0.8907, 0.6934],
         [0.9311, 0.9307, 0.7757],
         [0.9893, 0.9816, 0.9453]]), tensor([[9, 7, 2],
         [5, 6, 0],
         [7, 9, 3],
         [3, 6, 1]]))

In [282]:
a.topk(3, dim=1,largest=False)
##prod 最小的三个

(tensor([[0.1155, 0.2171, 0.2250],
         [0.1820, 0.3324, 0.3845],
         [0.0104, 0.0353, 0.0460],
         [0.0165, 0.2865, 0.3910]]), tensor([[5, 8, 3],
         [2, 7, 1],
         [4, 0, 2],
         [7, 9, 5]]))

In [284]:
a.kthvalue(8, dim=1)
## 第8小的，只能取小的， 第三大

(tensor([0.8563, 0.6934, 0.7757, 0.9453]), tensor([2, 0, 3, 1]))

In [287]:
a.kthvalue(8, dim=1, keepdim=True)

(tensor([[0.8563],
         [0.6934],
         [0.7757],
         [0.9453]]), tensor([[2],
         [0],
         [3],
         [1]]))

### Compare
 +  >=, <, >, <=, !=, ==


In [292]:
a

tensor([[0.5774, 0.7515, 0.8563, 0.2250, 0.3197, 0.1155, 0.6165, 0.8676, 0.2171,
         0.9897],
        [0.6934, 0.3845, 0.1820, 0.4120, 0.5332, 0.9099, 0.8907, 0.3324, 0.5976,
         0.5443],
        [0.0353, 0.6544, 0.0460, 0.7757, 0.0104, 0.5841, 0.1869, 0.9311, 0.6368,
         0.9307],
        [0.4991, 0.9453, 0.7833, 0.9893, 0.9156, 0.3910, 0.9816, 0.0165, 0.4856,
         0.2865]])

In [288]:
torch.equal(a,a)

True

In [289]:
torch.eq(a,a)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)

In [290]:
a!=0

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)

In [293]:
a>0.5

tensor([[1, 1, 1, 0, 0, 0, 1, 1, 0, 1],
        [1, 0, 0, 0, 1, 1, 1, 0, 1, 1],
        [0, 1, 0, 1, 0, 1, 0, 1, 1, 1],
        [0, 1, 1, 1, 1, 0, 1, 0, 0, 0]], dtype=torch.uint8)

### 高阶操作
+ where: torch.where(condition, x, y), 这个API目的是为了用GPU不然python的 if for 都是CPU的
+ gather：torch.gather(input, dim, index, out=None) :就是一个查表的过程
gather的第一个参数就是这个表 要查的内容（按照一定的index排好）， 第二个是哪个维度上查表， 第三个维度是要查的obs的index

out[ i ][ j ][ k ] = input[ i ][ j ][ index[ i ][ j ][ k ]]

应用： 4*10 的prod 的output 但是需要查表找到类别

In [294]:
prob = torch.randn(4,10)
prob

tensor([[-0.4996,  0.2912,  0.4303, -1.3786, -0.7375,  1.6539,  0.2789,  1.1537,
         -1.0621, -1.0559],
        [-1.4272, -0.7851, -1.0174,  1.3732,  0.2591,  0.4120,  1.9609,  0.9012,
         -1.4566, -0.7009],
        [-0.5012,  0.1862,  1.6809, -1.9056,  0.3141,  0.6699,  0.5370,  0.3954,
         -1.0066,  0.3865],
        [ 0.8548, -0.1116, -0.6496,  0.4982, -0.5505,  0.0507,  1.2021,  0.3614,
         -0.7943,  0.9540]])

In [298]:
idx = prob.topk(dim=1, k=3)
idx

(tensor([[1.6539, 1.1537, 0.4303],
         [1.9609, 1.3732, 0.9012],
         [1.6809, 0.6699, 0.5370],
         [1.2021, 0.9540, 0.8548]]), tensor([[5, 7, 2],
         [6, 3, 7],
         [2, 5, 6],
         [6, 9, 0]]))

In [299]:
idx[1]

tensor([[5, 7, 2],
        [6, 3, 7],
        [2, 5, 6],
        [6, 9, 0]])

In [300]:
label = torch.arange(10)+100
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [315]:
torch.gather(label.expand(4,10), dim=1, index=idx.long())

AttributeError: 'tuple' object has no attribute 'long'

In [317]:
import torch 
print(torch.__version__)

1.0.0


In [313]:
t = torch.tensor([[1,2],[3,4]])
t

tensor([[1, 2],
        [3, 4]])

In [314]:
torch.gather(t, 1, torch.tensor([[0,0],[1,0]]))

tensor([[1, 1],
        [4, 3]])

In [306]:
?torch.gather()

In [307]:
### Session 4 随机梯度下降
### Session 5 神经网络与全连接
### Session 6 过拟合